# Generated by Django 2.1.5 on 2019-03-11 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0002_auto_20190222_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
